scriptDir = fileparts(mfilename('fullpath'));
repoRoot = fileparts(scriptDir);
addpath(scriptDir);
cd(repoRoot);
run('startup.m');

validationDir = fullfile(tempdir, 'behaviorbox_wheel_setup_eye_alignment_validation');
if ~isfolder(validationDir)
    mkdir(validationDir);
end

app = MockApp();
gui = struct('MsgBox', app.MsgBox, 'NotesText', app.NotesText);
wheel = BehaviorBoxWheel(gui, app);
wheel.Box.Input_type = 6;
wheel.a = MockArduino();
wheel.Time = MockTime();
wheel.Setting_Struct.Subject = "999995";
wheel.Setting_Struct.Strain = "New";
wheel.Setting_Struct.One_ScanImage_File = true;
wheel.Setting_Struct.Weight = NaN;
wheel.TimeScanImageFileIndex = 1;
wheel.FrameAlignedRecord = makeEmptyFrameAlignedRecord_();

wheel.TrainStartWallClock = datetime(2026, 3, 27, 12, 20, 0);
wheel.TrainStartTime = tic;
wheel.EyeTrack = BehaviorBoxEyeTrack( ...
    Address="tcp://127.0.0.1:5555", ...
    SourceMode="localhost");
wheel.EyeTrack.setSessionClock(wheel.TrainStartTime, wheel.TrainStartWallClock);
wheel.EyeTrack.appendImportedSegmentForTest( ...
    makeEyeSegmentTable_(0, [2000000; 4000000], [201; 202], [10.0; 20.0], [0; 10]), ...
    makeEyeSegmentMeta_("setup_segment_1", "setup", 0, "setup"));
wheel.EyeTrack.appendImportedSegmentForTest( ...
    makeEyeSegmentTable_(1, [12000000; 12500000], [301; 302], [30.0; 40.0], [20; 30]), ...
    makeEyeSegmentMeta_("trial_1", "trial", 1, "training"));

setupParsed = table( ...
    ["annotation"; "annotation"; "frame"; "frame"], ...
    ["screen_on"; "acq_start"; "frame"; "frame"], ...
    [1500000; 1600000; 2500000; 4500000], ...
    [0; 0; 0; 0], ...
    [1; 1; 1; 1], ...
    [NaN; NaN; 11; 12], ...
    [NaN; NaN; 2499900; 4499900], ...
    [NaN; NaN; 2500100; 4500100], ...
    'VariableNames', {'kind', 'event', 't_us', 'trial', 'scanImageFile', 'frame', 't_arduino_us', 't_pc_receive_us'});
setupSegment = struct( ...
    'trial', 0, ...
    'kind', "setup", ...
    'scanImageFile', 1, ...
    'raw', ["screen_on"; "acq_start"; "frame"; "frame"], ...
    'parsed', setupParsed);

trialParsed = table( ...
    ["annotation"; "annotation"; "frame"; "frame"], ...
    ["trial_start"; "hold_still_start"; "frame"; "frame"], ...
    [11000000; 11100000; 12100000; 12600000], ...
    [1; 1; 1; 1], ...
    [1; 1; 1; 1], ...
    [NaN; NaN; 21; 22], ...
    [NaN; NaN; 12099000; 12599000], ...
    [NaN; NaN; 12100100; 12600100], ...
    'VariableNames', {'kind', 'event', 't_us', 'trial', 'scanImageFile', 'frame', 't_arduino_us', 't_pc_receive_us'});
trialSegment = struct( ...
    'trial', 1, ...
    'kind', "trial", ...
    'scanImageFile', 1, ...
    'raw', ["trial_start"; "hold_still_start"; "frame"; "frame"], ...
    'parsed', trialParsed);

wheel.timestamps_record = {setupSegment, trialSegment};
wheel.FrameAlignedRecord = makeFrameAlignedRows_( ...
    [0; 0; 1; 1], ...
    [11; 12; 21; 22], ...
    [2500000; 4500000; 12100000; 12600000], ...
    [2499900; 4499900; 12099000; 12599000], ...
    [2500100; 4500100; 12100100; 12600100], ...
    ["setup"; "setup"; "hold_still"; "response"], ...
    [NaN; NaN; 0.1; 0.6], ...
    [NaN; NaN; 20; 30], ...
    [NaN; NaN; 0; 10], ...
    [NaN; NaN; 0.7; 0.9], ...
    ["screen_on"; "acq_start"; "hold_still_start"; "choice_left"], ...
    [NaN; NaN; 5; 5], ...
    [false; false; true; true], ...
    [""; ""; "left"; "left"], ...
    [NaN; NaN; 1; 1]);

wheel.WheelDisplayRecord = table( ...
    [1; 1], ...
    [11100000; 12400000], ...
    ["hold_still"; "response"], ...
    [0.0; 1.3], ...
    [0; 10], ...
    [0.0; 0.4], ...
    [0.7; 0.9], ...
    ["hold_still_start"; "choice_left"], ...
    [5; 5], ...
    [true; true], ...
    'VariableNames', {'trial', 't_us', 'phase', 'tTrial', 'rawWheel', 'delta', 'StimColor', 'screenEvent', 'level', 'isLeftTrial'});

newData = BehaviorBoxData.new_init_data_struct();
newData.TrialNum = 1;
newData.SmallBin = 1;
newData.BigBin = 1;
newData.TimeStamp = 1.5;
newData.Score = 1;
newData.Level = 5;
newData.isLeftTrial = true;
newData.CodedChoice = 1;
newData.SetIdx = 1;
newData.RewardPulses = 1;
newData.InterTMal = 0;
newData.DuringTMal = 0;
newData.TrialStartTime = 0.1;
newData.ResponseTime = 0.2;
newData.DrinkTime = 0.3;
newData.isTraining = 0;
newData.SideBias = 0;
newData.BetweenTrialTime = 0.4;
newData.SetStr = "";
newData.SetUpdate = 0;
newData.Settings = struct();
newData.RewardTime = 0.3;
newData.WhatDecision = "left correct OC";
newData.LevelGroups = 5;
newData.StimHist = cell(0, 2);
newData.wheel_record = cell(0, 3);
newData.Include = 1;

wheel.Data_Object = struct( ...
    'current_data_struct', newData, ...
    'start_time', datetime(2026, 3, 27, 12, 20, 0), ...
    'Str', "New", ...
    'filedir', validationDir);

wheel.SaveAllData();

saveFile = fullfile(validationDir, '260327_122000_999995_New_Contour_Wheel.mat');
loaded = load(saveFile, 'newData');

frameTbl = loaded.newData.FrameAlignedRecord;
assert(~isempty(frameTbl) && height(frameTbl) >= 2, 'Expected saved frame-backed rows.');
setupMask = frameTbl.trial == 0;
assert(sum(setupMask) == 2, 'Expected two saved setup frame rows.');
assert(all(~isnan(frameTbl.eye_frame_id(setupMask))), 'Setup frames should align to setup eye samples.');
assert(all(frameTbl.phase(setupMask) == "setup"), 'Setup frame rows should keep setup phase.');

eyeTbl = loaded.newData.EyeAlignedRecord;
setupEyeMask = eyeTbl.trial == 0;
assert(sum(setupEyeMask) == 2, 'Expected two setup eye rows in EyeAlignedRecord.');
assert(all(eyeTbl.phase(setupEyeMask) == "setup"), 'Setup eye rows should keep setup phase.');
assert(all(~isnan(eyeTbl.nextMicroscopeFrame(setupEyeMask))), ...
    'Setup eye rows should point to later microscope frames.');
assert(eyeTbl.nextMicroscopeFrame(find(setupEyeMask, 1, 'first')) == 11, ...
    'First setup eye row should point to the first later setup frame.');

disp("BEHAVIORBOX_WHEEL_SETUP_EYE_ALIGNMENT_OK");

function tbl = makeEyeSegmentTable_(trialNumber, tUs, frameIds, centerX, pointOffset)
rows(numel(tUs),1) = defaultRowStruct_(trialNumber, tUs(1), frameIds(1), centerX(1), pointOffset(1));
for idx = 1:numel(tUs)
    rows(idx,1) = defaultRowStruct_(trialNumber, tUs(idx), frameIds(idx), centerX(idx), pointOffset(idx));
end
tbl = struct2table(rows);
tbl = tbl(:, cellstr(BehaviorBoxEyeTrack.recordVariableNames()));
end

function meta = makeEyeSegmentMeta_(segmentId, segmentKind, trialNumber, modeName)
meta = struct( ...
    'segment_id', string(segmentId), ...
    'segment_kind', string(segmentKind), ...
    'trial_number', double(trialNumber), ...
    'mode', string(modeName), ...
    'scan_image_file', 1, ...
    'csv_path', "", ...
    'metadata_path', "", ...
    'closed', true, ...
    'partial', false, ...
    'point_names', {cellstr(BehaviorBoxEyeTrack.defaultPointNames())});
end

function row = defaultRowStruct_(trialNumber, tUs, frameId, centerX, pointOffset)
captureUnixS = 1776001200.100000 + (double(tUs) / 1e6);
publishUnixS = captureUnixS + 0.020000;
captureUnixNs = string(sprintf('%.0f', captureUnixS * 1e9));
publishUnixNs = string(sprintf('%.0f', publishUnixS * 1e9));
centerY = centerX + 0.5;
diameterPx = 30.0 + (pointOffset / 10.0);
diameterHPx = diameterPx + 1.1;
diameterVPx = diameterPx - 1.1;
row = struct( ...
    'trial', double(trialNumber), ...
    't_us', double(tUs), ...
    't_receive_us', double(tUs), ...
    'frame_id', double(frameId), ...
    'capture_time_unix_s', double(captureUnixS), ...
    'capture_time_unix_ns', captureUnixNs, ...
    'publish_time_unix_s', double(publishUnixS), ...
    'publish_time_unix_ns', publishUnixNs, ...
    'center_x', double(centerX), ...
    'center_y', double(centerY), ...
    'diameter_px', double(diameterPx), ...
    'diameter_h_px', double(diameterHPx), ...
    'diameter_v_px', double(diameterVPx), ...
    'confidence_mean', 0.97, ...
    'valid_points', 8, ...
    'camera_fps', 120.0, ...
    'inference_fps', 60.0, ...
    'latency_ms', 9.2, ...
    'is_valid', true, ...
    'sample_status', "ok", ...
    'Lpupil_x', double(pointOffset + 1), 'Lpupil_y', double(pointOffset + 2), 'Lpupil_likelihood', 0.91, ...
    'LDpupil_x', double(pointOffset + 2), 'LDpupil_y', double(pointOffset + 3), 'LDpupil_likelihood', 0.92, ...
    'Dpupil_x', double(pointOffset + 3), 'Dpupil_y', double(pointOffset + 4), 'Dpupil_likelihood', 0.93, ...
    'DRpupil_x', double(pointOffset + 4), 'DRpupil_y', double(pointOffset + 5), 'DRpupil_likelihood', 0.94, ...
    'Rpupil_x', double(pointOffset + 5), 'Rpupil_y', double(pointOffset + 6), 'Rpupil_likelihood', 0.95, ...
    'RVpupil_x', double(pointOffset + 6), 'RVpupil_y', double(pointOffset + 7), 'RVpupil_likelihood', 0.96, ...
    'Vpupil_x', double(pointOffset + 7), 'Vpupil_y', double(pointOffset + 8), 'Vpupil_likelihood', 0.97, ...
    'VLpupil_x', double(pointOffset + 8), 'VLpupil_y', double(pointOffset + 9), 'VLpupil_likelihood', 0.98);
end

function tbl = makeEmptyFrameAlignedRecord_()
tbl = table( ...
    'Size', [0 15], ...
    'VariableTypes', {'double','double','double','double','double','string','double','double','double','double','string','double','logical','string','double'}, ...
    'VariableNames', {'trial','frame','t_us','t_arduino_us','t_pc_receive_us','phase','tTrial','rawWheel','delta','StimColor','screenEvent','level','isLeftTrial','decision','correct'});
tbl = BehaviorBoxEyeTrack.alignEyeSamplesToTable(BehaviorBoxEyeTrack.emptyRecordTable(), tbl);
end

function tbl = makeFrameAlignedRows_(trial, frame, tUs, tArduinoUs, tPcReceiveUs, phase, tTrial, rawWheel, delta, stimColor, screenEvent, level, isLeftTrial, decision, correct)
tbl = table( ...
    double(trial(:)), ...
    double(frame(:)), ...
    double(tUs(:)), ...
    double(tArduinoUs(:)), ...
    double(tPcReceiveUs(:)), ...
    string(phase(:)), ...
    double(tTrial(:)), ...
    double(rawWheel(:)), ...
    double(delta(:)), ...
    double(stimColor(:)), ...
    string(screenEvent(:)), ...
    double(level(:)), ...
    logical(isLeftTrial(:)), ...
    string(decision(:)), ...
    double(correct(:)), ...
    'VariableNames', {'trial','frame','t_us','t_arduino_us','t_pc_receive_us','phase','tTrial','rawWheel','delta','StimColor','screenEvent','level','isLeftTrial','decision','correct'});
tbl = BehaviorBoxEyeTrack.alignEyeSamplesToTable(BehaviorBoxEyeTrack.emptyRecordTable(), tbl);
end
