scriptDir = fileparts(mfilename('fullpath'));
repoRoot = fileparts(scriptDir);
addpath(scriptDir);
cd(repoRoot);
run('startup.m');

validationDir = fullfile(tempdir, 'behaviorbox_wheel_mapping_save_validation');
if ~isfolder(validationDir)
    mkdir(validationDir);
end

app = MockApp();
gui = struct('MsgBox', app.MsgBox, 'NotesText', app.NotesText);
wheel = BehaviorBoxWheel(gui, app);
wheel.Setting_Struct.Subject = "999997";
wheel.Setting_Struct.Strain = "New";
wheel.Data_Object = struct( ...
    'start_time', datetime(2026, 3, 27, 12, 10, 0), ...
    'Str', "New", ...
    'filedir', validationDir);
wheel.TrainStartWallClock = datetime(2026, 3, 27, 12, 10, 0);
wheel.TrainStartTime = tic;
wheel.EyeTrack = BehaviorBoxEyeTrack( ...
    Address="tcp://127.0.0.1:5555", ...
    SourceMode="localhost", ...
    BridgeDir=fullfile(repoRoot, "EyeTrack", "DeepLabCut", "ToMatlab"));
wheel.EyeTrack.setSessionClock(wheel.TrainStartTime, wheel.TrainStartWallClock);
wheel.EyeTrack.processReading(makeEyeJson_(wheel.TrainStartWallClock, 118000, 11, 10.0, 0), 0);
wheel.EyeTrack.processReading(makeEyeJson_(wheel.TrainStartWallClock, 132000, 12, 20.0, 10), 0);
wheel.EyeTrack.processReading(makeEyeJson_(wheel.TrainStartWallClock, 158000, 13, 30.0, 20), 0);

timestampParsed = table( ...
    ["frame"; "frame"], ...
    ["frame"; "frame"], ...
    [130000; 160000], ...
    [0; 0], ...
    [1; 1], ...
    [101; 102], ...
    [129500; 159500], ...
    [130100; 160100], ...
    'VariableNames', {'kind', 'event', 't_us', 'trial', 'scanImageFile', 'frame', 't_arduino_us', 't_pc_receive_us'});
timestampRecord = {struct( ...
    'trial', 0, ...
    'kind', "mapping", ...
    'scanImageFile', 1, ...
    'raw', ["frame"; "frame"], ...
    'parsed', timestampParsed)};

mapLog = table( ...
    [10000; 15000; 20000; 90000; 100000; 105000; 110000; 120000; 130000; 140000; 145000; 155000], ...
    ["AcquisitionStart"; "DisplayOn"; "SettleStart"; "State"; "SettleEnd"; "SequenceStart"; "CycleStart"; ...
     "FlashOn"; "State"; "RewardGiven"; "FlashOff"; "State"], ...
    repmat("FlashContourX", 12, 1), ...
    [NaN; NaN; NaN; NaN; NaN; NaN; NaN; -0.5; -0.5; NaN; -0.5; -0.5], ...
    [NaN; NaN; NaN; NaN; NaN; NaN; NaN; 0; 0; NaN; 0; 0], ...
    [NaN; NaN; NaN; NaN; NaN; NaN; 45; 45; 45; NaN; 45; 45], ...
    [NaN; NaN; NaN; NaN; NaN; NaN; NaN; 1; 1; NaN; 1; 1], ...
    [NaN; NaN; NaN; NaN; NaN; NaN; NaN; NaN; 0.30; 0.90; NaN; 0.05], ...
    [""; ""; ""; ""; ""; ""; ""; "Correct"; "Correct"; ""; "Correct"; "Correct"], ...
    [""; ""; ""; "settle"; ""; ""; "cycle=1"; "level=8"; "level=8"; "side=R"; "level=8"; "hidden level=8"], ...
    'VariableNames', {'t_us','event','mode','x','y','angleDeg','scale','brightness','variant','notes'});

wheel.SaveAllData("Activity", "Animate", "PosRecord", [], ...
    "TimeLog", string.empty(0,1), ...
    "MapLog", mapLog, ...
    "MapMeta", struct('Style', "Map-FlashContourX"), ...
    "TimestampRecord", timestampRecord);

saveFile = fullfile(validationDir, '260327_121000_999997_New_Animate_Wheel.mat');
loaded = load(saveFile);

assert(isfield(loaded, 'EyeTrackingRecord'), 'Mapping save is missing EyeTrackingRecord.');
assert(isfield(loaded, 'EyeTrackingMeta'), 'Mapping save is missing EyeTrackingMeta.');
assert(isfield(loaded, 'FrameAlignedRecord'), 'Mapping save is missing FrameAlignedRecord.');
assert(isfield(loaded, 'EyeAlignedRecord'), 'Mapping save is missing EyeAlignedRecord.');

assert(height(loaded.EyeTrackingRecord) == 3, 'Mapping save should retain all dense eye samples.');
assert(~any(startsWith(string(loaded.MapLog.Properties.VariableNames), "eye_")), ...
    'Raw MapLog should not be mutated with eye-alignment columns.');

expectedPointColumns = [ ...
    "Lpupil_x", "Lpupil_y", "Lpupil_likelihood", ...
    "LDpupil_x", "LDpupil_y", "LDpupil_likelihood", ...
    "Dpupil_x", "Dpupil_y", "Dpupil_likelihood", ...
    "DRpupil_x", "DRpupil_y", "DRpupil_likelihood", ...
    "Rpupil_x", "Rpupil_y", "Rpupil_likelihood", ...
    "RVpupil_x", "RVpupil_y", "RVpupil_likelihood", ...
    "Vpupil_x", "Vpupil_y", "Vpupil_likelihood", ...
    "VLpupil_x", "VLpupil_y", "VLpupil_likelihood"];
eyeAlignedVars = string(loaded.EyeAlignedRecord.Properties.VariableNames);
assert(all(ismember(expectedPointColumns, eyeAlignedVars)), ...
    'EyeAlignedRecord is missing exact YangLab pupil8 point columns.');
assert(all(ismember(["nextMicroscopeFrame", "nextMicroscopeFrame_t_us", "nextMicroscopeFrame_t_arduino_us", ...
    "nextMicroscopeFrame_t_pc_receive_us", "nextMicroscopeFrame_dt_us"], eyeAlignedVars)), ...
    'EyeAlignedRecord is missing microscope back-reference columns.');

frameVars = string(loaded.FrameAlignedRecord.Properties.VariableNames);
assert(all(ismember(["mode", "level", "variant", "x", "y", "angleDeg", "scale", "brightness", ...
    "eye_center_x", "eye_center_y", "eye_sample_count"], frameVars)), ...
    'FrameAlignedRecord is missing mapping state or aligned-eye columns.');

assert(height(loaded.FrameAlignedRecord) == 2, 'Expected one frame-aligned row per microscope frame.');
assert(loaded.FrameAlignedRecord.eye_center_x(1) == 10.0, 'First frame should align to the most recent previous eye sample.');
assert(loaded.FrameAlignedRecord.eye_center_x(2) == 30.0, 'Second frame should align to the most recent previous eye sample.');
assert(loaded.FrameAlignedRecord.phase(1) == "flash", 'First frame should be labeled as flash phase.');
assert(loaded.FrameAlignedRecord.phase(2) == "interflash", 'Second frame should be labeled as interflash phase.');
assert(loaded.FrameAlignedRecord.level(1) == 8, 'Flash level should be reconstructed from MapLog notes.');
assert(loaded.FrameAlignedRecord.variant(1) == "Correct", 'Flash variant should be reconstructed from MapLog.');
assert(contains(loaded.FrameAlignedRecord.screenEvent(1), "FlashOn"), 'First frame should include FlashOn in screenEvent.');
assert(contains(loaded.FrameAlignedRecord.screenEvent(2), "RewardGiven"), 'Second frame should include RewardGiven in screenEvent.');
assert(contains(loaded.FrameAlignedRecord.screenEvent(2), "FlashOff"), 'Second frame should include FlashOff in screenEvent.');

assert(height(loaded.EyeAlignedRecord) == 3, 'Expected one eye-aligned row per eye sample.');
assert(loaded.EyeAlignedRecord.center_x(1) == 10.0, 'EyeAlignedRecord should preserve raw eye sample values.');
assert(loaded.EyeAlignedRecord.center_x(3) == 30.0, 'EyeAlignedRecord should preserve later raw eye sample values.');
assert(loaded.EyeAlignedRecord.VLpupil_x(3) == 28, 'EyeAlignedRecord should retain exact raw DLC point values.');
assert(loaded.EyeAlignedRecord.screenEvent_count(2) == 1, 'Second eye sample should capture one screen event in its interval.');
assert(loaded.EyeAlignedRecord.screenEvent(2) == "FlashOn", 'Second eye sample should align FlashOn to the eye-backed table.');
assert(contains(loaded.EyeAlignedRecord.screenEvent(3), "RewardGiven"), 'Third eye sample should include RewardGiven.');
assert(contains(loaded.EyeAlignedRecord.screenEvent(3), "FlashOff"), 'Third eye sample should include FlashOff.');
assert(loaded.EyeAlignedRecord.phase(2) == "flash", 'Second eye sample should be labeled as flash phase.');
assert(loaded.EyeAlignedRecord.phase(3) == "interflash", 'Third eye sample should be labeled as interflash phase.');
assert(loaded.EyeAlignedRecord.nextMicroscopeFrame(1) == 101, 'First eye sample should point to the first later microscope frame.');
assert(loaded.EyeAlignedRecord.nextMicroscopeFrame(2) == 102, 'Second eye sample should point to the second microscope frame.');
assert(loaded.EyeAlignedRecord.nextMicroscopeFrame(3) == 102, 'Third eye sample should still point to the next later microscope frame.');
assert(abs(loaded.EyeAlignedRecord.nextMicroscopeFrame_dt_us(1) - 12000) <= 1, 'First eye sample frame lag is wrong.');
assert(abs(loaded.EyeAlignedRecord.nextMicroscopeFrame_dt_us(3) - 2000) <= 1, 'Third eye sample frame lag is wrong.');

appNoEye = MockApp();
guiNoEye = struct('MsgBox', appNoEye.MsgBox, 'NotesText', appNoEye.NotesText);
wheelNoEye = BehaviorBoxWheel(guiNoEye, appNoEye);
wheelNoEye.Setting_Struct.Subject = "999996";
wheelNoEye.Setting_Struct.Strain = "New";
wheelNoEye.Data_Object = struct( ...
    'start_time', datetime(2026, 3, 27, 12, 11, 0), ...
    'Str', "New", ...
    'filedir', validationDir);
wheelNoEye.TrainStartWallClock = datetime(2026, 3, 27, 12, 11, 0);
wheelNoEye.TrainStartTime = tic;

wheelNoEye.SaveAllData("Activity", "Animate", "PosRecord", [], ...
    "TimeLog", string.empty(0,1), ...
    "MapLog", mapLog, ...
    "MapMeta", struct('Style', "Map-FlashContourX"), ...
    "TimestampRecord", timestampRecord);

saveFileNoEye = fullfile(validationDir, '260327_121100_999996_New_Animate_Wheel.mat');
loadedNoEye = load(saveFileNoEye);
assert(isfield(loadedNoEye, 'EyeTrackingRecord'), 'No-eye mapping save should still write EyeTrackingRecord.');
assert(height(loadedNoEye.EyeTrackingRecord) == 0, 'No-eye mapping save should write an empty EyeTrackingRecord.');
assert(~isfield(loadedNoEye, 'EyeAlignedRecord'), 'No-eye mapping save should omit EyeAlignedRecord.');
assert(isfield(loadedNoEye, 'FrameAlignedRecord'), 'No-eye mapping save should still write FrameAlignedRecord when timestamps exist.');
assert(height(loadedNoEye.FrameAlignedRecord) == 2, 'No-eye mapping save should still keep microscope-backed frame rows.');
assert(all(isnan(loadedNoEye.FrameAlignedRecord.eye_center_x)), 'No-eye frame-aligned rows should have empty aligned-eye values.');

disp("BEHAVIORBOX_WHEEL_MAPPING_SAVE_OK");

function jsonText = makeEyeJson_(sessionStartWallClock, offsetUs, frameId, centerX, pointOffset)
captureTimeUnixS = posixtime(sessionStartWallClock) + (double(offsetUs) / 1e6);
publishTimeUnixS = captureTimeUnixS + 0.100000;
captureTimeUnixNs = sprintf('%.0f', captureTimeUnixS * 1e9);
publishTimeUnixNs = sprintf('%.0f', publishTimeUnixS * 1e9);
centerY = centerX + 0.5;
diameterPx = 30.0 + (pointOffset / 10.0);
diameterHPx = diameterPx + 1.1;
diameterVPx = diameterPx - 1.1;
jsonText = [
    "{", ...
    """message_type"":""sample"",", ...
    """schema_version"":1,", ...
    """sample_status"":""ok"",", ...
    """source"":""dlc_eye_streamer"",", ...
    """model_preset"":""yanglab-pupil8"",", ...
    """model_type"":""base"",", ...
    """frame_id"":" + string(frameId) + ",", ...
    """capture_time_unix_s"":" + string(sprintf('%.6f', captureTimeUnixS)) + ",", ...
    """capture_time_unix_ns"":" + string(captureTimeUnixNs) + ",", ...
    """publish_time_unix_s"":" + string(sprintf('%.6f', publishTimeUnixS)) + ",", ...
    """publish_time_unix_ns"":" + string(publishTimeUnixNs) + ",", ...
    """camera_fps"":120.0,", ...
    """inference_fps"":60.0,", ...
    """latency_ms"":9.2,", ...
    """center_x"":" + string(sprintf('%.1f', centerX)) + ",", ...
    """center_y"":" + string(sprintf('%.1f', centerY)) + ",", ...
    """diameter_px"":" + string(sprintf('%.1f', diameterPx)) + ",", ...
    """diameter_h_px"":" + string(sprintf('%.1f', diameterHPx)) + ",", ...
    """diameter_v_px"":" + string(sprintf('%.1f', diameterVPx)) + ",", ...
    """confidence_mean"":0.97,", ...
    """valid_points"":8,", ...
    """point_names"":[""Lpupil"",""LDpupil"",""Dpupil"",""DRpupil"",""Rpupil"",""RVpupil"",""Vpupil"",""VLpupil""],", ...
    """point_count"":8,", ...
    """points"":{", ...
    """Lpupil"":[" + string(pointOffset + 1) + "," + string(pointOffset + 2) + ",0.91],", ...
    """LDpupil"":[" + string(pointOffset + 2) + "," + string(pointOffset + 3) + ",0.92],", ...
    """Dpupil"":[" + string(pointOffset + 3) + "," + string(pointOffset + 4) + ",0.93],", ...
    """DRpupil"":[" + string(pointOffset + 4) + "," + string(pointOffset + 5) + ",0.94],", ...
    """Rpupil"":[" + string(pointOffset + 5) + "," + string(pointOffset + 6) + ",0.95],", ...
    """RVpupil"":[" + string(pointOffset + 6) + "," + string(pointOffset + 7) + ",0.96],", ...
    """Vpupil"":[" + string(pointOffset + 7) + "," + string(pointOffset + 8) + ",0.97],", ...
    """VLpupil"":[" + string(pointOffset + 8) + "," + string(pointOffset + 9) + ",0.98]", ...
    "}", ...
    "}"];
jsonText = join(jsonText, "");
end
