scriptDir = fileparts(mfilename('fullpath'));
repoRoot = fileparts(scriptDir);
addpath(scriptDir);
cd(repoRoot);
run('startup.m');

validationDir = fullfile(tempdir, 'behaviorbox_wheel_save_validation');
if ~isfolder(validationDir)
    mkdir(validationDir);
end

app = MockApp();
gui = struct('MsgBox', app.MsgBox, 'NotesText', app.NotesText);
wheel = BehaviorBoxWheel(gui, app);
wheel.Box.Input_type = 6;
wheel.a = MockArduino();
wheel.Time = MockTime();
wheel.Setting_Struct.Subject = "999999";
wheel.Setting_Struct.Strain = "New";
wheel.Setting_Struct.One_ScanImage_File = true;
wheel.Setting_Struct.Weight = NaN;
wheel.TimeScanImageFileIndex = 2;

trialParsed = table( ...
    repmat("annotation", 2, 1), ...
    ["trial_start"; "trial_end"], ...
    [100; 200], ...
    [1; 1], ...
    [1; 1], ...
    'VariableNames', {'kind', 'event', 't_us', 'trial', 'scanImageFile'});
wheel.timestamps_record = {struct( ...
    'trial', 1, ...
    'kind', "trial", ...
    'scanImageFile', 1, ...
    'raw', ["trial_start"; "trial_end"], ...
    'parsed', trialParsed)};

wheel.Time.RawLog = ["trial_start"; "choice_left"];
wheel.Time.Log = wheel.Time.RawLog;
wheel.Time.ParsedLog = table( ...
    repmat("annotation", 2, 1), ...
    ["trial_start"; "choice_left"], ...
    [300; 400], ...
    [2; 2], ...
    [2; 2], ...
    'VariableNames', {'kind', 'event', 't_us', 'trial', 'scanImageFile'});
wheel.TimeSegmentKind = "trial";
wheel.TimeSegmentTrial = 2;
wheel.FrameAlignedRecord = makeEmptyFrameAlignedRecord_();

wheel.EyeTrack = BehaviorBoxEyeTrack( ...
    Address="tcp://127.0.0.1:5555", ...
    SourceMode="localhost");
wheel.EyeTrack.setSessionClock(tic, datetime(2026, 3, 27, 12, 0, 0));
wheel.EyeTrack.appendImportedSegmentForTest( ...
    makeEyeSegmentTable_(2, 150, 24, 11.1, 0), ...
    makeEyeSegmentMeta_("train_trial_2", "trial", 2, "training"));

wheel.WheelDisplayRecord = table( ...
    [1; 2], ...
    [100; 200], ...
    ["reward"; "reward"], ...
    [0.5; 0.6], ...
    [1; 2], ...
    [0.1; 0.2], ...
    [0.8; 0.9], ...
    ["reward_on"; "reward_on"], ...
    [5; 5], ...
    [true; true], ...
    'VariableNames', {'trial', 't_us', 'phase', 'tTrial', 'rawWheel', 'delta', 'StimColor', 'screenEvent', 'level', 'isLeftTrial'});

wheel.cleanUP();

assert(numel(wheel.timestamps_record) == 3, 'Expected committed trial, active trial, and cleanup segments.');
assert(strcmp(string(wheel.timestamps_record{2}.kind), "trial"), 'Active trial segment was not preserved.');
assert(wheel.timestamps_record{2}.trial == 2, 'Preserved active segment has wrong trial number.');
assert(strcmp(string(wheel.timestamps_record{3}.kind), "cleanup"), 'Cleanup segment missing after cleanUP.');
assert(isnan(wheel.timestamps_record{3}.trial), 'Cleanup segment should be session-level (NaN trial).');

newData = BehaviorBoxData.new_init_data_struct();
newData.TrialNum = 1;
newData.SmallBin = 1;
newData.BigBin = 1;
newData.TimeStamp = 1.5;
newData.Score = 1;
newData.Level = 5;
newData.isLeftTrial = true;
newData.CodedChoice = 1;
newData.SetIdx = 1;
newData.RewardPulses = 1;
newData.InterTMal = 0;
newData.DuringTMal = 0;
newData.TrialStartTime = 0.1;
newData.ResponseTime = 0.2;
newData.DrinkTime = 0.3;
newData.isTraining = 0;
newData.SideBias = 0;
newData.BetweenTrialTime = 0.4;
newData.SetStr = "";
newData.SetUpdate = 0;
newData.Settings = struct();
newData.RewardTime = 0.3;
newData.WhatDecision = "left correct OC";
newData.LevelGroups = 5;
newData.StimHist = cell(0, 2);
newData.wheel_record = cell(0, 3);
newData.Include = 1;

wheel.Data_Object = struct( ...
    'current_data_struct', newData, ...
    'start_time', datetime(2026, 3, 27, 12, 0, 0), ...
    'Str', "New", ...
    'filedir', validationDir);

wheel.SaveAllData();

saveFile = fullfile(validationDir, '260327_120000_999999_New_Contour_Wheel.mat');
loaded = load(saveFile, 'newData');

wheelVars = string(loaded.newData.WheelDisplayRecord.Properties.VariableNames);
assert(all(ismember(["trialCommitted", "trialStatus"], wheelVars)), 'WheelDisplayRecord status columns missing.');
assert(loaded.newData.WheelDisplayRecord.trialCommitted(1), 'Committed wheel trial should be marked committed.');
assert(loaded.newData.WheelDisplayRecord.trialStatus(2) == "in_progress", 'Uncommitted wheel trial should be marked in_progress.');

assert(loaded.newData.TimestampRecord{1}.trialStatus == "committed", 'Committed timestamp segment status is wrong.');
assert(~loaded.newData.TimestampRecord{2}.trialCommitted, 'Uncommitted timestamp segment should not be marked committed.');
assert(loaded.newData.TimestampRecord{2}.trialStatus == "in_progress", 'Active timestamp segment status is wrong.');
assert(loaded.newData.TimestampRecord{3}.trialStatus == "session", 'Cleanup timestamp segment should be session-level.');
assert(all(loaded.newData.TimestampRecord{2}.parsed.trialStatus == "in_progress"), 'Parsed active timestamp rows are missing status annotations.');

assert(isfield(loaded.newData, 'EyeTrackingRecord'), 'EyeTrackingRecord missing from saved data.');
assert(isfield(loaded.newData, 'EyeTrackingMeta'), 'EyeTrackingMeta missing from saved data.');
assert(isfield(loaded.newData, 'EyeTrackRecord'), 'EyeTrackRecord missing from saved data.');
assert(isfield(loaded.newData, 'EyeTrackSegmentMeta'), 'EyeTrackSegmentMeta missing from saved data.');
assert(height(loaded.newData.EyeTrackingRecord) == 1, 'Expected one saved eye-tracking sample.');
assert(numel(loaded.newData.EyeTrackRecord) == 1, 'Training save should retain one per-segment eye table.');
assert(all(ismember(["Lpupil_x", "RVpupil_y", "VLpupil_likelihood"], string(loaded.newData.EyeTrackingRecord.Properties.VariableNames))), ...
    'Saved eye-point columns are missing.');
assert(loaded.newData.EyeTrackingMeta.PointCount == 8, 'Saved eye metadata should report 8 tracked points.');
assert(isfield(loaded.newData, 'EyeAlignedRecord'), 'Training save should include EyeAlignedRecord when eye samples exist.');
assert(height(loaded.newData.EyeAlignedRecord) == 1, 'Training EyeAlignedRecord should retain one eye-backed row.');
assert(isnan(loaded.newData.EyeAlignedRecord.nextMicroscopeFrame(1)), ...
    'Training EyeAlignedRecord microscope back-reference should be empty when no frame rows exist.');

assert(~isfield(loaded.newData, 'FrameAlignedRecord'), ...
    'Training save should omit FrameAlignedRecord when no frame-backed rows were derived.');
wheelVars = string(loaded.newData.WheelDisplayRecord.Properties.VariableNames);
assert(all(ismember(["eye_center_x", "eye_center_y", "eye_sample_count"], wheelVars)), ...
    'WheelDisplayRecord eye columns are missing.');

animationDir = fullfile(tempdir, 'behaviorbox_wheel_animation_validation');
if ~isfolder(animationDir)
    mkdir(animationDir);
end
appAnim = MockApp();
guiAnim = struct('MsgBox', appAnim.MsgBox, 'NotesText', appAnim.NotesText);
wheelAnim = BehaviorBoxWheel(guiAnim, appAnim);
wheelAnim.Setting_Struct.Subject = "999998";
wheelAnim.Setting_Struct.Strain = "New";
wheelAnim.Data_Object = struct( ...
    'start_time', datetime(2026, 3, 27, 12, 5, 0), ...
    'Str', "New", ...
    'filedir', animationDir);
wheelAnim.TrainStartWallClock = datetime(2026, 3, 27, 12, 5, 0);
wheelAnim.TrainStartTime = tic;
wheelAnim.EyeTrack = BehaviorBoxEyeTrack( ...
    Address="tcp://127.0.0.1:5555", ...
    SourceMode="localhost");
wheelAnim.EyeTrack.setSessionClock(wheelAnim.TrainStartTime, wheelAnim.TrainStartWallClock);
wheelAnim.EyeTrack.appendImportedSegmentForTest( ...
    makeEyeSegmentTable_(0, 100, 24, 11.1, 0), ...
    makeEyeSegmentMeta_("animate_segment_1", "mapping", 0, "Map-SweepLine"));

mapLog = table( ...
    [50; 150], ...
    ["State"; "State"], ...
    ["Sweep"; "Sweep"], ...
    [0.1; 0.2], ...
    [0.0; 0.0], ...
    [90; 90], ...
    [1; 1], ...
    [NaN; NaN], ...
    [""; ""], ...
    [""; ""], ...
    'VariableNames', {'t_us','event','mode','x','y','angleDeg','scale','brightness','variant','notes'});
wheelAnim.SaveAllData("Activity", "Animate", "PosRecord", [], ...
    "TimeLog", string.empty(0,1), "MapLog", mapLog, ...
    "MapMeta", struct('Style', "Map-SweepLine"), "TimestampRecord", {});
animationFile = fullfile(animationDir, '260327_120500_999998_New_Animate_Wheel.mat');
loadedAnimation = load(animationFile);
assert(isfield(loadedAnimation, 'EyeTrackingRecord'), 'Animation save is missing EyeTrackingRecord.');
assert(isfield(loadedAnimation, 'EyeTrackingMeta'), 'Animation save is missing EyeTrackingMeta.');
assert(isfield(loadedAnimation, 'EyeTrackRecord'), 'Animation save is missing EyeTrackRecord.');
assert(isfield(loadedAnimation, 'EyeTrackSegmentMeta'), 'Animation save is missing EyeTrackSegmentMeta.');
assert(height(loadedAnimation.EyeTrackingRecord) == 1, 'Animation save should retain dense eye samples.');
assert(numel(loadedAnimation.EyeTrackRecord) == 1, 'Animation save should retain one per-segment eye table.');
assert(~any(startsWith(string(loadedAnimation.MapLog.Properties.VariableNames), "eye_")), ...
    'Animation MapLog should remain the raw mapping-event table.');
assert(~isfield(loadedAnimation, 'FrameAlignedRecord'), ...
    'Animation save should omit FrameAlignedRecord when there are no microscope frame rows.');
assert(isfield(loadedAnimation, 'EyeAlignedRecord'), 'Animation save is missing EyeAlignedRecord.');
assert(height(loadedAnimation.EyeAlignedRecord) == 1, 'Animation save should retain one eye-aligned row.');
assert(loadedAnimation.EyeAlignedRecord.center_x(1) == 11.1, 'EyeAlignedRecord should preserve the raw eye sample values.');
assert(isnan(loadedAnimation.EyeAlignedRecord.nextMicroscopeFrame(1)), ...
    'EyeAlignedRecord microscope back-reference should be empty when no frame rows exist.');
assert(loadedAnimation.MapMeta.EyeTrackingSampleCount == 1, 'Animation MapMeta should record the dense eye sample count.');

app2 = MockApp();
gui2 = struct('MsgBox', app2.MsgBox, 'NotesText', app2.NotesText);
wheel2 = BehaviorBoxWheel(gui2, app2);
wheel2.Box.Input_type = 6;
wheel2.a = MockArduino();
wheel2.Time = MockTime();
wheel2.Setting_Struct.One_ScanImage_File = false;
wheel2.Setting_Struct.Weight = NaN;
wheel2.TimeScanImageFileIndex = 4;
wheel2.Time.RawLog = "trial_start";
wheel2.Time.Log = wheel2.Time.RawLog;
wheel2.Time.ParsedLog = table( ...
    "annotation", ...
    "trial_start", ...
    500, ...
    4, ...
    4, ...
    'VariableNames', {'kind', 'event', 't_us', 'trial', 'scanImageFile'});
wheel2.TimeSegmentKind = "trial";
wheel2.TimeSegmentTrial = 4;

wheel2.cleanUP();

assert(isscalar(wheel2.timestamps_record), 'Per-trial cleanup should preserve the active segment.');
assert(wheel2.timestamps_record{1}.trial == 4, 'Per-trial cleanup stored the wrong trial number.');
assert(any(string(wheel2.timestamps_record{1}.parsed.event) == "acq_end"), 'Per-trial cleanup should append acq_end before storing.');

disp("BEHAVIORBOX_WHEEL_SAVE_STATUS_OK");

function tbl = makeEyeSegmentTable_(trialNumber, tUs, frameId, centerX, pointOffset)
tbl = struct2table(defaultRowStruct_(trialNumber, tUs, frameId, centerX, pointOffset));
tbl = tbl(:, cellstr(BehaviorBoxEyeTrack.recordVariableNames()));
end

function meta = makeEyeSegmentMeta_(segmentId, segmentKind, trialNumber, modeName)
meta = struct( ...
    'segment_id', string(segmentId), ...
    'segment_kind', string(segmentKind), ...
    'trial_number', double(trialNumber), ...
    'mode', string(modeName), ...
    'scan_image_file', NaN, ...
    'csv_path', "", ...
    'metadata_path', "", ...
    'closed', true, ...
    'partial', false, ...
    'point_names', {cellstr(BehaviorBoxEyeTrack.defaultPointNames())});
end

function row = defaultRowStruct_(trialNumber, tUs, frameId, centerX, pointOffset)
centerY = centerX + 11.1;
diameterPx = 33.3 + pointOffset;
diameterHPx = diameterPx + 1.1;
diameterVPx = diameterPx - 1.1;
captureUnixS = 1776000000.100000 + (double(tUs) / 1e6);
publishUnixS = captureUnixS + 0.020000;
captureUnixNs = string(sprintf('%.0f', captureUnixS * 1e9));
publishUnixNs = string(sprintf('%.0f', publishUnixS * 1e9));
row = struct( ...
    'trial', double(trialNumber), ...
    't_us', double(tUs), ...
    't_receive_us', double(tUs), ...
    'frame_id', double(frameId), ...
    'capture_time_unix_s', double(captureUnixS), ...
    'capture_time_unix_ns', captureUnixNs, ...
    'publish_time_unix_s', double(publishUnixS), ...
    'publish_time_unix_ns', publishUnixNs, ...
    'center_x', double(centerX), ...
    'center_y', double(centerY), ...
    'diameter_px', double(diameterPx), ...
    'diameter_h_px', double(diameterHPx), ...
    'diameter_v_px', double(diameterVPx), ...
    'confidence_mean', 0.97, ...
    'valid_points', 8, ...
    'camera_fps', 120.0, ...
    'inference_fps', 60.0, ...
    'latency_ms', 9.2, ...
    'is_valid', true, ...
    'sample_status', "ok", ...
    'Lpupil_x', double(pointOffset + 1), 'Lpupil_y', double(pointOffset + 2), 'Lpupil_likelihood', 0.91, ...
    'LDpupil_x', double(pointOffset + 2), 'LDpupil_y', double(pointOffset + 3), 'LDpupil_likelihood', 0.92, ...
    'Dpupil_x', double(pointOffset + 3), 'Dpupil_y', double(pointOffset + 4), 'Dpupil_likelihood', 0.93, ...
    'DRpupil_x', double(pointOffset + 4), 'DRpupil_y', double(pointOffset + 5), 'DRpupil_likelihood', 0.94, ...
    'Rpupil_x', double(pointOffset + 5), 'Rpupil_y', double(pointOffset + 6), 'Rpupil_likelihood', 0.95, ...
    'RVpupil_x', double(pointOffset + 6), 'RVpupil_y', double(pointOffset + 7), 'RVpupil_likelihood', 0.96, ...
    'Vpupil_x', double(pointOffset + 7), 'Vpupil_y', double(pointOffset + 8), 'Vpupil_likelihood', 0.97, ...
    'VLpupil_x', double(pointOffset + 8), 'VLpupil_y', double(pointOffset + 9), 'VLpupil_likelihood', 0.98);
end

function tbl = makeEmptyFrameAlignedRecord_()
tbl = table( ...
    'Size', [0 15], ...
    'VariableTypes', {'double','double','double','double','double','string','double','double','double','double','string','double','logical','string','double'}, ...
    'VariableNames', {'trial','frame','t_us','t_arduino_us','t_pc_receive_us','phase','tTrial','rawWheel','delta','StimColor','screenEvent','level','isLeftTrial','decision','correct'});
tbl = BehaviorBoxEyeTrack.alignEyeSamplesToTable(BehaviorBoxEyeTrack.emptyRecordTable(), tbl);
end
