% Wheel (only 16p males)
% W = BehaviorBoxData(Inv='Will', Inp='Wheel', Sub={'251742'}, BB=20, SB=10);
% W.GroupData



%X = BehaviorBoxData(Inv='Will', Inp='NosePoke', Sub={'1234568'}, BB=20, SB=10);

%X = BehaviorBoxData(Inv='Will', Inp='NosePoke', Sub={'2822464'}, BB=20, SB=10);

%Sh = BehaviorBoxData(Inv='Will', Inp='NosePoke', Sub={'shank'}, BB=20, SB=10);



% Females, nose
F = BehaviorBoxDataNew(Inv='Will', Inp='NosePoke', Sub={'- F -'}, BB=20, SB=10);
M = BehaviorBoxDataNew(Inv='Will', Inp='NosePoke', Sub={'- M -'}, BB=20, SB=10);
F.GroupData( ...
    "Composite",false, ...
    'LevGroup',false, ...
    'History',true, ...
    'Stim',false, ...
    'LevelProgress',true, ...
    'LevelProgressIndividual',true, ...
    'Save',true)
% Males, nose
M.GroupData( ...
    "Composite",false, ...
    'LevGroup',false, ...
    'History',true, ...
    'Stim',false, ...
    'LevelProgress',true, ...
    'LevelProgressIndividual',true, ...
    'Save',true)