% Females, nose
F = BehaviorBoxDataNew(Inv='Will', Inp='NosePoke', Sub={'- F -'}, BB=20, SB=10);
M = BehaviorBoxDataNew(Inv='Will', Inp='NosePoke', Sub={'- M -'}, BB=20, SB=10);
F.GroupData( ...
    "Composite",false, ...
    'LevGroup',false, ...
    'History',false, ...
    'Stim',false, ...
    'LevelProgress',true, ...
    'LevelProgressIndividual',true, ...
    'Save',true, ...
    'FileName','')
% Males, nose
M.GroupData( ...
    "Composite",false, ...
    'LevGroup',false, ...
    'History',false, ...
    'Stim',false, ...
    'LevelProgress',true, ...
    'LevelProgressIndividual',true, ...
    'Save',true, ...
    'FileName','')