scriptDir = fileparts(mfilename('fullpath'));
repoRoot = fileparts(scriptDir);
cd(repoRoot);
run('startup.m');

bridgeState = struct( ...
    'Messages', {[makeMetadataJson_(), makeEyeJson_(42), makeEyeJson_(43)]}, ...
    'NextIndex', 0, ...
    'Opened', false, ...
    'Closed', false);
setappdata(0, 'BBEyeTrackTestBridgeState', bridgeState);

bridgeAdapter = struct( ...
    'open_subscriber', @openSubscriber_, ...
    'recv_all_json', @recvAllJson_, ...
    'close_socket', @closeSocket_);

eyeTrack = BehaviorBoxEyeTrack( ...
    Address="tcp://127.0.0.1:5555", ...
    SourceMode="localhost", ...
    BridgeDir=fullfile(repoRoot, "EyeTrack", "DeepLabCut", "ToMatlab"), ...
    BridgeAdapter=bridgeAdapter, ...
    StartTimerOnStart=false);
eyeTrack.setSessionClock(tic, datetime(1736891233, 'ConvertFrom', 'posixtime'));
eyeTrack.markTrial(7);
assert(eyeTrack.start(), 'EyeTrack subscriber failed to start through the bridge adapter.');
assert(eyeTrack.IsConnected, 'EyeTrack should report a live subscriber connection after start.');
assert(eyeTrack.IsReady, 'EyeTrack should become ready after a valid sample.');

record = eyeTrack.getRecord();
assert(height(record) == 2, 'Expected start() to drain both queued eye-tracking samples.');
assert(all(record.trial == 7), 'Eye-tracking trial tags are wrong.');
assert(isequal(record.frame_id(:), [42; 43]), 'Eye-tracking frame ids are wrong.');
assert(record.capture_time_unix_ns(1) == "1736891234567890123", 'Capture ns text was not preserved exactly.');
assert(record.publish_time_unix_ns(1) == "1736891234567999999", 'Publish ns text was not preserved exactly.');
assert(record.sample_status(1) == "ok", 'Valid eye payload should parse as ok.');
assert(record.is_valid(1), 'Valid eye payload should be marked valid.');
assert(abs(record.Lpupil_x(1) - 10.5) < 1e-9, 'Lpupil_x is wrong.');
assert(abs(record.VLpupil_likelihood(1) - 0.98) < 1e-9, 'VLpupil_likelihood is wrong.');
assert(abs(record.RVpupil_y(1) - 61.5) < 1e-9, 'RVpupil_y is wrong.');

meta = eyeTrack.getMeta();
assert(meta.SourceMode == "localhost", 'EyeTrack source mode is wrong.');
assert(meta.BridgeAvailable, 'Expected EyeTrack bridge directory to exist in this repo.');
assert(numel(meta.PointNames) == 8, 'Expected fixed 8-point model metadata.');
assert(meta.MessagesReceived == 3, 'Expected one metadata message plus two eye samples.');
assert(meta.MetadataMessagesReceived == 1, 'Expected one stream metadata message.');
assert(meta.SamplesReceived == 2, 'Expected two sample messages.');
assert(meta.CsvPath == "/tmp/eye_stream_test.csv", 'Expected CSV path in eye metadata.');
assert(~meta.TimerRunning, 'Test adapter run should not start a timer.');

target = table([record.t_us(1); record.t_us(2)], [1; 2], 'VariableNames', {'t_us','frame'});
aligned = BehaviorBoxEyeTrack.alignEyeSamplesToTable(record, target, 'Mode', 'interval_summary');
assert(all(ismember(["eye_frame_id", "eye_sample_count", "eye_center_x_mean"], string(aligned.Properties.VariableNames))), ...
    'Alignment helper did not add expected eye columns.');
assert(aligned.eye_frame_id(2) == 43, 'Previous alignment selected the wrong representative sample.');
assert(aligned.eye_sample_count(2) >= 1, 'Interval summary sample count is wrong.');

bridgeState = getappdata(0, 'BBEyeTrackTestBridgeState');
assert(bridgeState.Opened, 'Bridge adapter should have opened a subscriber socket.');

eyeTrack.processReading("{bad_json", 7);
recordAfterBadJson = eyeTrack.getRecord();
assert(height(recordAfterBadJson) == 2, 'Invalid JSON should not append an eye sample row.');

eyeTrack.stop();
bridgeState = getappdata(0, 'BBEyeTrackTestBridgeState');
assert(bridgeState.Closed, 'Bridge adapter should have closed the subscriber socket.');
rmappdata(0, 'BBEyeTrackTestBridgeState');

disp("BEHAVIORBOX_EYETRACK_OK");

function jsonText = makeMetadataJson_()
payload = struct( ...
    'message_type', 'metadata', ...
    'schema_version', 1, ...
    'source', 'dlc_eye_streamer', ...
    'model_preset', 'yanglab-pupil8', ...
    'model_type', 'base', ...
    'point_names', {cellstr(BehaviorBoxEyeTrack.defaultPointNames())}, ...
    'point_count', 8, ...
    'csv_path', '/tmp/eye_stream_test.csv');
jsonText = string(jsonencode(payload));
end

function jsonText = makeEyeJson_(frameId)
if frameId == 42
    captureNs = "1736891234567890123";
    publishNs = "1736891234567999999";
else
    captureNs = "1736891234568890123";
    publishNs = "1736891234568999999";
end
captureS = str2double(captureNs) / 1e9;
publishS = str2double(publishNs) / 1e9;
payload = struct( ...
    'message_type', 'sample', ...
    'schema_version', 1, ...
    'sample_status', 'ok', ...
    'source', 'dlc_eye_streamer', ...
    'model_preset', 'yanglab-pupil8', ...
    'model_type', 'base', ...
    'frame_id', frameId, ...
    'capture_time_unix_s', captureS, ...
    'capture_time_unix_ns', captureNs, ...
    'publish_time_unix_s', publishS, ...
    'publish_time_unix_ns', publishNs, ...
    'camera_fps', 119.8, ...
    'inference_fps', 58.4, ...
    'latency_ms', 8.6, ...
    'center_x', 45.5, ...
    'center_y', 55.5, ...
    'diameter_px', 23.4, ...
    'diameter_h_px', 24.5, ...
    'diameter_v_px', 22.3, ...
    'confidence_mean', 0.95, ...
    'valid_points', 8, ...
    'point_names', {cellstr(BehaviorBoxEyeTrack.defaultPointNames())}, ...
    'point_count', 8, ...
    'points', struct( ...
        'Lpupil', [10.5, 11.5, 0.91], ...
        'LDpupil', [20.5, 21.5, 0.92], ...
        'Dpupil', [30.5, 31.5, 0.93], ...
        'DRpupil', [40.5, 41.5, 0.94], ...
        'Rpupil', [50.5, 51.5, 0.95], ...
        'RVpupil', [60.5, 61.5, 0.96], ...
        'Vpupil', [70.5, 71.5, 0.97], ...
        'VLpupil', [80.5, 81.5, 0.98]));
jsonText = string(jsonencode(payload));
end

function socket = openSubscriber_(address, rcvhwm)
socket = struct('Address', string(address), 'RcvHwm', double(rcvhwm));
state = getappdata(0, 'BBEyeTrackTestBridgeState');
state.Opened = true;
setappdata(0, 'BBEyeTrackTestBridgeState', state);
end

function jsonText = recvAllJson_(~, ~, ~)
state = getappdata(0, 'BBEyeTrackTestBridgeState');
state.NextIndex = state.NextIndex + 1;
if state.NextIndex == 1
    jsonText = "[" + strjoin(string(state.Messages), ",") + "]";
else
    jsonText = "[]";
end
setappdata(0, 'BBEyeTrackTestBridgeState', state);
end

function closeSocket_(~)
state = getappdata(0, 'BBEyeTrackTestBridgeState');
state.Closed = true;
setappdata(0, 'BBEyeTrackTestBridgeState', state);
end
