scriptDir = fileparts(mfilename('fullpath'));
repoRoot = fileparts(scriptDir);
cd(repoRoot);
run('startup.m');

tmpRoot = fullfile(tempdir, 'behaviorbox_eye_import_test');
if ~isfolder(tmpRoot)
    mkdir(tmpRoot);
end
chunkCsv = fullfile(tmpRoot, 'segment_0001.csv');
chunkMeta = fullfile(tmpRoot, 'segment_0001_metadata.json');
manifest = struct( ...
    'segment_id', "segment_0001", ...
    'segment_kind', "trial", ...
    'trial_number', 7, ...
    'mode', "training", ...
    'scan_image_file', 1, ...
    'csv_path', string(chunkCsv), ...
    'metadata_path', string(chunkMeta), ...
    'receive_start_unix_ns', 1776000000100000000, ...
    'receive_end_unix_ns', 1776000000120000000, ...
    't_receive_start_us', 100, ...
    't_receive_end_us', 120, ...
    'row_count', 2, ...
    'closed', true, ...
    'partial', false, ...
    'point_names', {cellstr(BehaviorBoxEyeTrack.defaultPointNames())});

record = makeEyeSegmentTable_();
writetable(record, chunkCsv);
fid = fopen(chunkMeta, 'w');
fprintf(fid, '%s', jsonencode(manifest));
fclose(fid);

adapterState = struct( ...
    'Started', false, ...
    'Opened', false, ...
    'Closed', false, ...
    'Finalized', false, ...
    'Stopped', false, ...
    'Manifest', manifest);
setappdata(0, 'BBEyeTrackReceiverAdapterState', adapterState);

clientAdapter = struct( ...
    'health', @health_, ...
    'session_start', @sessionStart_, ...
    'segment_open', @segmentOpen_, ...
    'segment_close', @segmentClose_, ...
    'session_finalize', @sessionFinalize_, ...
    'session_stop', @sessionStop_, ...
    'manifest', @manifest_);

eyeTrack = BehaviorBoxEyeTrack( ...
    Address="tcp://127.0.0.1:5555", ...
    SourceMode="localhost", ...
    ReceiverUrl="http://127.0.0.1:8765", ...
    ClientAdapter=clientAdapter);
eyeTrack.setSessionClock(tic, datetime(1776000000, 'ConvertFrom', 'posixtime'));
eyeTrack.configureSession( ...
    "SessionId", "test_eye_session", ...
    "SessionKind", "training", ...
    "SessionLabel", "eye-import-test", ...
    "OutputDir", tmpRoot);

assert(eyeTrack.start(), 'EyeTrack receiver client failed to start.');
assert(eyeTrack.beginSegment("SegmentId", "segment_0001", "SegmentKind", "trial", "TrialNumber", 7, "Mode", "training", "ScanImageFile", 1), ...
    'EyeTrack receiver client failed to open the trial segment.');
eyeTrack.closeSegment();
eyeTrack.finalizeSession();

record = eyeTrack.getRecord();
assert(height(record) == 2, 'Deferred import should have produced two eye rows.');
assert(all(record.trial == 7), 'Imported eye rows have the wrong trial number.');
assert(isequal(record.frame_id(:), [42; 43]), 'Imported eye frame ids are wrong.');
assert(record.capture_time_unix_ns(1) == "1776000000100000000", 'Capture ns text was not preserved exactly.');
assert(record.publish_time_unix_ns(1) == "1776000000120000000", 'Publish ns text was not preserved exactly.');
assert(abs(record.Lpupil_x(1) - 10.5) < 1e-9, 'Lpupil_x is wrong.');
assert(abs(record.VLpupil_likelihood(1) - 0.98) < 1e-9, 'VLpupil_likelihood is wrong.');
assert(abs(record.RVpupil_y(1) - 61.5) < 1e-9, 'RVpupil_y is wrong.');

meta = eyeTrack.getMeta();
assert(meta.SourceMode == "localhost", 'EyeTrack source mode is wrong.');
assert(meta.PointCount == 8, 'Expected fixed 8-point model metadata.');
assert(meta.SamplesReceived == 2, 'Expected two imported eye samples.');
assert(meta.AlignmentTimeColumn == "t_receive_us", 'Expected receive-time alignment metadata.');
assert(meta.CsvPath == string(chunkCsv), 'Expected CSV path in eye metadata.');
assert(meta.MetadataPath == string(chunkMeta), 'Expected sidecar metadata path in eye metadata.');
assert(numel(meta.ImportedSegmentIds) == 1, 'Expected one imported segment id.');

target = table([100; 120], [1; 2], 'VariableNames', {'t_us','frame'});
aligned = BehaviorBoxEyeTrack.alignEyeSamplesToTable(record, target, 'Mode', 'interval_summary');
assert(all(ismember(["eye_frame_id", "eye_sample_count", "eye_center_x_mean"], string(aligned.Properties.VariableNames))), ...
    'Alignment helper did not add expected eye columns.');
assert(aligned.eye_frame_id(2) == 43, 'Previous alignment selected the wrong representative sample.');
assert(aligned.eye_sample_count(2) >= 1, 'Interval summary sample count is wrong.');

adapterState = getappdata(0, 'BBEyeTrackReceiverAdapterState');
assert(adapterState.Started, 'Receiver adapter should have observed session start.');
assert(adapterState.Opened, 'Receiver adapter should have observed segment open.');
assert(adapterState.Closed, 'Receiver adapter should have observed segment close.');
assert(adapterState.Finalized, 'Receiver adapter should have observed session finalize.');

eyeTrack.stop();
adapterState = getappdata(0, 'BBEyeTrackReceiverAdapterState');
assert(adapterState.Stopped, 'Receiver adapter should have observed session stop.');
rmappdata(0, 'BBEyeTrackReceiverAdapterState');

disp("BEHAVIORBOX_EYETRACK_OK");

function tbl = makeEyeSegmentTable_()
rows = [
    rowStruct_(7, 100, 42, 10.5, 0.98, 1776000000.10, 1776000000.12)
    rowStruct_(7, 120, 43, 20.5, 0.88, 1776000000.11, 1776000000.13)];
tbl = struct2table(rows);
tbl = tbl(:, cellstr(BehaviorBoxEyeTrack.recordVariableNames()));
end

function row = rowStruct_(trialNumber, tUs, frameId, centerX, vLpupilLikelihood, captureUnixS, publishUnixS)
captureUnixNs = string(sprintf('%.0f', captureUnixS * 1e9));
publishUnixNs = string(sprintf('%.0f', publishUnixS * 1e9));
row = struct( ...
    'trial', double(trialNumber), ...
    't_us', double(tUs), ...
    't_receive_us', double(tUs), ...
    'frame_id', double(frameId), ...
    'capture_time_unix_s', double(captureUnixS), ...
    'capture_time_unix_ns', captureUnixNs, ...
    'publish_time_unix_s', double(publishUnixS), ...
    'publish_time_unix_ns', publishUnixNs, ...
    'center_x', double(centerX), ...
    'center_y', 55.5, ...
    'diameter_px', 23.4, ...
    'diameter_h_px', 24.5, ...
    'diameter_v_px', 22.3, ...
    'confidence_mean', 0.95, ...
    'valid_points', 8, ...
    'camera_fps', 119.8, ...
    'inference_fps', 58.4, ...
    'latency_ms', 8.6, ...
    'is_valid', true, ...
    'sample_status', "ok", ...
    'Lpupil_x', 10.5, 'Lpupil_y', 11.5, 'Lpupil_likelihood', 0.91, ...
    'LDpupil_x', 20.5, 'LDpupil_y', 21.5, 'LDpupil_likelihood', 0.92, ...
    'Dpupil_x', 30.5, 'Dpupil_y', 31.5, 'Dpupil_likelihood', 0.93, ...
    'DRpupil_x', 40.5, 'DRpupil_y', 41.5, 'DRpupil_likelihood', 0.94, ...
    'Rpupil_x', 50.5, 'Rpupil_y', 51.5, 'Rpupil_likelihood', 0.95, ...
    'RVpupil_x', 60.5, 'RVpupil_y', 61.5, 'RVpupil_likelihood', 0.96, ...
    'Vpupil_x', 70.5, 'Vpupil_y', 71.5, 'Vpupil_likelihood', 0.97, ...
    'VLpupil_x', 80.5, 'VLpupil_y', 81.5, 'VLpupil_likelihood', vLpupilLikelihood);
end

function payload = health_(~)
payload = struct( ...
    'ok', true, ...
    'point_names', {cellstr(BehaviorBoxEyeTrack.defaultPointNames())}, ...
    'model_name', "yanglab-pupil8");
end

function payload = sessionStart_(~)
state = getappdata(0, 'BBEyeTrackReceiverAdapterState');
state.Started = true;
setappdata(0, 'BBEyeTrackReceiverAdapterState', state);
payload = struct( ...
    'point_names', {cellstr(BehaviorBoxEyeTrack.defaultPointNames())}, ...
    'model_name', "yanglab-pupil8");
end

function payload = segmentOpen_(body)
state = getappdata(0, 'BBEyeTrackReceiverAdapterState');
state.Opened = true;
setappdata(0, 'BBEyeTrackReceiverAdapterState', state);
payload = struct( ...
    'session_id', string(body.session_id), ...
    'segment_id', string(body.segment_id), ...
    'segment_kind', string(body.segment_kind));
end

function payload = segmentClose_(body)
state = getappdata(0, 'BBEyeTrackReceiverAdapterState');
state.Closed = true;
setappdata(0, 'BBEyeTrackReceiverAdapterState', state);
payload = struct( ...
    'session_id', string(body.session_id), ...
    'segment_id', "segment_0001", ...
    'closed', true);
end

function payload = sessionFinalize_(body)
state = getappdata(0, 'BBEyeTrackReceiverAdapterState');
state.Finalized = true;
setappdata(0, 'BBEyeTrackReceiverAdapterState', state);
payload = struct('session_id', string(body.session_id));
end

function payload = sessionStop_(body)
state = getappdata(0, 'BBEyeTrackReceiverAdapterState');
state.Stopped = true;
setappdata(0, 'BBEyeTrackReceiverAdapterState', state);
payload = struct('session_id', string(body.session_id));
end

function payload = manifest_(~)
state = getappdata(0, 'BBEyeTrackReceiverAdapterState');
payload = struct( ...
    'session_id', "test_eye_session", ...
    'segments', state.Manifest);
end
