scriptDir = fileparts(mfilename('fullpath'));
repoRoot = fileparts(scriptDir);
cd(repoRoot);
run('startup.m');

bridgeState = struct( ...
    'Messages', {makeEyeJson_()}, ...
    'NextIndex', 0, ...
    'Opened', false, ...
    'Closed', false);
setappdata(0, 'BBEyeTrackTestBridgeState', bridgeState);

bridgeAdapter = struct( ...
    'open_subscriber', @openSubscriber_, ...
    'recv_latest_json', @recvLatestJson_, ...
    'close_socket', @closeSocket_);

eyeTrack = BehaviorBoxEyeTrack( ...
    Address="tcp://127.0.0.1:5555", ...
    SourceMode="localhost", ...
    BridgeDir=fullfile(repoRoot, "EyeTrack", "DeepLabCut", "ToMatlab"), ...
    BridgeAdapter=bridgeAdapter, ...
    StartTimerOnStart=false);
eyeTrack.setSessionClock(tic, datetime(2026, 4, 15, 12, 0, 0));
assert(eyeTrack.start(), 'EyeTrack subscriber failed to start through the bridge adapter.');
assert(eyeTrack.IsConnected, 'EyeTrack should report a live subscriber connection after start.');
assert(eyeTrack.pollAvailable(7) == 1, 'Expected one bridged eye-tracking message.');

record = eyeTrack.getRecord();
assert(height(record) == 1, 'Expected one eye-tracking sample.');
assert(record.trial(1) == 7, 'Eye-tracking trial tag is wrong.');
assert(record.frame_id(1) == 42, 'Eye-tracking frame id is wrong.');
assert(record.capture_time_unix_ns(1) == "1736891234567890123", 'Capture ns text was not preserved exactly.');
assert(record.publish_time_unix_ns(1) == "1736891234567999999", 'Publish ns text was not preserved exactly.');
assert(record.sampleStatus(1) == "ok", 'Valid eye payload should parse as ok.');
assert(record.isValid(1), 'Valid eye payload should be marked valid.');

pointsXyp = record.points_xyp{1};
assert(isequal(size(pointsXyp), [8 3]), 'Expected an 8x3 eye-point matrix.');
assert(all(abs(pointsXyp(1,:) - [10.5 11.5 0.91]) < 1e-9), 'Lpupil row is wrong.');
assert(all(abs(pointsXyp(8,:) - [80.5 81.5 0.98]) < 1e-9), 'VLpupil row is wrong.');

meta = eyeTrack.getMeta();
assert(meta.SourceMode == "localhost", 'EyeTrack source mode is wrong.');
assert(meta.BridgeAvailable, 'Expected EyeTrack bridge directory to exist in this repo.');
assert(numel(meta.PointNames) == 8, 'Expected fixed 8-point model metadata.');
assert(meta.MessagesReceived == 1, 'Expected one subscriber-delivered eye sample.');
assert(~meta.TimerRunning, 'Test adapter run should not start a timer.');

bridgeState = getappdata(0, 'BBEyeTrackTestBridgeState');
assert(bridgeState.Opened, 'Bridge adapter should have opened a subscriber socket.');

eyeTrack.processReading("{bad_json", 7);
record = eyeTrack.getRecord();
assert(height(record) == 2, 'Invalid JSON should still append a raw-log row.');
assert(record.sampleStatus(2) == "invalid_json", 'Invalid JSON row status is wrong.');
assert(isequal(size(record.points_xyp{2}), [8 3]), 'Invalid JSON row should keep the fixed 8x3 point shape.');
assert(all(all(isnan(record.points_xyp{2}))), 'Invalid JSON row should keep NaN eye points.');

eyeTrack.stop();
bridgeState = getappdata(0, 'BBEyeTrackTestBridgeState');
assert(bridgeState.Closed, 'Bridge adapter should have closed the subscriber socket.');
rmappdata(0, 'BBEyeTrackTestBridgeState');

disp("BEHAVIORBOX_EYETRACK_OK");

function jsonText = makeEyeJson_()
jsonText = [
    "{", ...
    """source"":""dlc_eye_streamer"",", ...
    """frame_id"":42,", ...
    """capture_time_unix_s"":1736891234.567890,", ...
    """capture_time_unix_ns"":1736891234567890123,", ...
    """publish_time_unix_s"":1736891234.679000,", ...
    """publish_time_unix_ns"":1736891234567999999,", ...
    """camera_fps"":119.8,", ...
    """inference_fps"":58.4,", ...
    """latency_ms"":8.6,", ...
    """center_x"":45.5,", ...
    """center_y"":55.5,", ...
    """diameter_px"":23.4,", ...
    """diameter_h_px"":24.5,", ...
    """diameter_v_px"":22.3,", ...
    """confidence_mean"":0.95,", ...
    """valid_points"":8,", ...
    """points"":{", ...
    """Lpupil"":[10.5,11.5,0.91],", ...
    """LDpupil"":[20.5,21.5,0.92],", ...
    """Dpupil"":[30.5,31.5,0.93],", ...
    """DRpupil"":[40.5,41.5,0.94],", ...
    """Rpupil"":[50.5,51.5,0.95],", ...
    """RVupil"":[60.5,61.5,0.96],", ...
    """Vpupil"":[70.5,71.5,0.97],", ...
    """VLpupil"":[80.5,81.5,0.98]", ...
    "}", ...
    "}"];
jsonText = join(jsonText, "");
end

function socket = openSubscriber_(address, rcvhwm)
socket = struct('Address', string(address), 'RcvHwm', double(rcvhwm));
state = getappdata(0, 'BBEyeTrackTestBridgeState');
state.Opened = true;
setappdata(0, 'BBEyeTrackTestBridgeState', state);
end

function jsonText = recvLatestJson_(~, ~)
state = getappdata(0, 'BBEyeTrackTestBridgeState');
state.NextIndex = state.NextIndex + 1;
if state.NextIndex <= numel(state.Messages)
    jsonText = string(state.Messages{state.NextIndex});
else
    jsonText = "";
end
setappdata(0, 'BBEyeTrackTestBridgeState', state);
end

function closeSocket_(~)
state = getappdata(0, 'BBEyeTrackTestBridgeState');
state.Closed = true;
setappdata(0, 'BBEyeTrackTestBridgeState', state);
end
